### ISSUE TITLE
how to

### ISSUE THREAD

**Issue by c0d3x27** [laaposto/GOViz#1]
if i take this and edit your code can i use it for the italian goverment?

**Comment by laaposto** [comment]
Yes, you can use it in any way you want. If you build a project based on this repo and you don't mind, please share it with me. I would be very interested to see the result.

**Comment by c0d3x27** [comment]
sure, i will try. thank you for your work. this is a very nice app, i think that if you make in a way that anyone can use it and just add their country into it, it could be very famous.

**Comment by laaposto** [comment]
Yeah, that would be super nice, but my free time is so limited now.
Thank you for your interest

**Comment by c0d3x27** [comment]
yeah, i understand time is always a problem. your welcome
